In [8]:
import torch
import torch.nn as nn

input_feat = torch.tensor([[4, 1, 7, 5], [4, 4, 2, 5], [7, 7, 2, 4], [1, 0, 2, 4]], dtype=torch.float32).unsqueeze(0).unsqueeze(0)
print(input_feat)
print(input_feat.shape)


tensor([[[[4., 1., 7., 5.],
          [4., 4., 2., 5.],
          [7., 7., 2., 4.],
          [1., 0., 2., 4.]]]])
torch.Size([1, 1, 4, 4])


In [9]:
conv2d = nn.Conv2d(1, 1, (2,2), stride=1, padding='same',bias=True)
print(conv2d.weight)
print(conv2d.bias)

# manually change the kernel
kernels = torch.tensor([[[[1,0],[2,1]]]], dtype=torch.float32)
conv2d.weight = nn.Parameter(kernels, requires_grad=False)
print(conv2d.weight)
print(conv2d.bias)

output_feat = conv2d(input_feat)
print(output_feat)
print(output_feat.shape)

Parameter containing:
tensor([[[[ 0.3296,  0.4516],
          [-0.1834,  0.4384]]]], requires_grad=True)
Parameter containing:
tensor([-0.1646], requires_grad=True)
Parameter containing:
tensor([[[[1., 0.],
          [2., 1.]]]])
Parameter containing:
tensor([-0.1646], requires_grad=True)
tensor([[[[15.8354, 10.8354, 15.8354, 14.8354],
          [24.8354, 19.8354,  9.8354, 12.8354],
          [ 8.8354,  8.8354,  9.8354, 11.8354],
          [ 0.8354, -0.1646,  1.8354,  3.8354]]]],
       grad_fn=<ConvolutionBackward0>)
torch.Size([1, 1, 4, 4])


/Users/liukang1/.pyenv/versions/3.10.9/lib/python3.10/site-packages/torch/nn/modules/conv.py:459: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Convolution.cpp:896.)
  return F.conv2d(input, weight, bias, self.stride,
