In [2]:
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):
    # constructor
    def __init__(self, data_tensor, target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor

    def __len__(self):
        return self.data_tensor.size(0)
    
    def __getitem__(self, index):
        return self.data_tensor[index], self.target_tensor[index]

In [3]:
data_tensor = torch.randn(10,3)
target_tensor = torch.randint(2,(10,)) # label

my_dataset = MyDataset(data_tensor, target_tensor)

print("Dataset size: ", len(my_dataset))
print("tensor_data[0]:", my_dataset[0])

Dataset size:  10
tensor_data[0]: (tensor([-0.1001, -1.0698, -0.2782]), tensor(1))


In [4]:
from torch.utils.data import DataLoader

tensor_dataloader = DataLoader(dataset=my_dataset, batch_size=2, shuffle=True, num_workers=0)
for data, target in tensor_dataloader:
    print(data, target)

tensor([[ 0.0830, -0.7627,  0.0866],
        [ 0.9518, -0.4725,  0.2719]]) tensor([1, 1])
tensor([[ 0.8953,  0.6716,  0.7002],
        [-0.8279,  0.4978,  1.6698]]) tensor([0, 1])
tensor([[-0.1001, -1.0698, -0.2782],
        [ 0.2641, -0.0154, -0.2795]]) tensor([1, 0])
tensor([[-0.3007,  1.1450,  0.3518],
        [-0.3168, -0.8301, -1.2342]]) tensor([0, 1])
tensor([[-1.4045,  1.0933,  1.6540],
        [-0.7879, -1.7702,  1.3259]]) tensor([1, 1])


In [7]:
print('One batch: ', next(iter(tensor_dataloader)))

One batch:  [tensor([[-0.3007,  1.1450,  0.3518],
        [-0.3168, -0.8301, -1.2342]]), tensor([0, 1])]


In [6]:
import torchvision

mnist_data = torchvision.datasets.MNIST(root='./data', train=True, transform=None, target_transform=None, download=True )
mnist_data_list = list(mnist_data)
display(mnist_data_list[0][0])
print("Image label is: ", mnist_data_list[0][1])

Image label is:  5
