In [2]:
import torch

A = torch.arange(0,16).view(4,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [3]:
B = torch.index_select(A, 0, torch.tensor([1,3]))
B

tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])

In [6]:
C = torch.index_select(A, 1, torch.tensor([0,3]))
C

tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])

In [7]:
X = torch.rand(5)
X

tensor([0.3413, 0.4029, 0.2096, 0.2892, 0.9544])

In [8]:
Y = torch.masked_select(X, X>0.3)
Y

tensor([0.3413, 0.4029, 0.9544])

In [10]:
A=torch.tensor([[4,5,7], [3,9,8],[2,3,4]])
A

tensor([[4, 5, 7],
        [3, 9, 8],
        [2, 3, 4]])

In [13]:
B=torch.masked_select(A, torch.tensor([[True, False, False],[True, True, False],[False, False, True]]))
B

tensor([4, 3, 9, 4])